application: ForecastAccuracy
version: 1.0a
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  script: Trunk/bbc_forecast_data.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
#- name: urllib3
#  version: "1.11"
