application: ForecastAccuracy
version: 1.0a
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: bbc_forecast_data.app

libraries:
#- name: jinja2
#  version: "2.6"
- name: markupsafe
  version: "0.15"

